### ISSUE TITLE
utils.js中有些疑问。

### ISSUE THREAD

**Issue by zhengjunxiang** [HelTi/webpack-M-pages#1]
```
var path = require('path');
const fs = require('fs');
/*设置生产环境与开发环境路径*/
exports.assetsPath = function (_path) {
    var assetsSubDirectory = process.env.NODE_ENV === 'production'
        ? 'static'
        : 'static'
    return path.posix.join(assetsSubDirectory, _path)
}
```
` var assetsSubDirectory = process.env.NODE_ENV === 'production'
        ? 'static'
        : 'static'`
判断当前是开发还是生产环境中，为什么都是 ` ? 'static' : 'static'` ,这样好像好像结果都是`static`, 不明白这里的意图，请解答下，多谢！

**Comment by HelTi** [comment]
你好，这是因为我开发环境和生产环境都设置的都是static文件夹，这个我是考虑开发环境，参照vue-cli写的，具体的开发环境我并没配置，因为我没分这么细。具体的你可以参考下vue-cli的配置
