### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by Tommychou** [HelTi/webpack-M-pages#3]
ERROR in static/js/pageAfa0a7cb370e67ff07729.js from UglifyJs
Unexpected token: name (urlParts) [static/js/pageAfa0a7cb370e67ff07729.js:252,4]

ERROR in static/js/pageCfa0a7cb370e67ff07729.js from UglifyJs
Unexpected token: name (urlParts) [static/js/pageCfa0a7cb370e67ff07729.js:252,4]

ERROR in static/js/pageBfa0a7cb370e67ff07729.js from UglifyJs
Unexpected token: name (urlParts) [static/js/pageBfa0a7cb370e67ff07729.js:252,4]

请问该如何解决？

还有一个问题就是引用common和lib里的js文件 可以打包到到当前引用的js文件中么

**Comment by mraiguo** [comment]
@Tommychou 我也遇到同样的问题了  在 mac的环境下，请问你解决了吗

**Comment by Tommychou** [comment]
没有 我不用这个了

**Comment by Tommychou** [comment]
没有 我不用这个了 @mraiguo

**Comment by mraiguo** [comment]
@Tommychou 请问有什么好的多页脚手架项目吗？ 我找了很多，发现都有这样那样的问题

**Comment by HelTi** [comment]
@Tommychou  已经更新到webpack3,你在试试
